# Generated by Django 5.0 on 2024-01-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactEquiry',
        ),
    ]
