# Generated by Django 5.0.1 on 2024-01-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='amount',
            new_name='amount_bill',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paid_amount',
            new_name='total_paid_amount',
        ),
    ]
