# Generated by Django 5.0.1 on 2024-01-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='employee_img'),
        ),
    ]
