# Generated by Django 5.0.1 on 2024-01-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_food_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
    ]
